name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: typescript tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

  test-action:
    name: Run action (latest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Run local action
        id: test-action
        uses: ./
      - name: Test installed tools
        run: |
          echo "opam: $(opam --version)"
          echo "ocamlc: $(ocamlc --version)"
          echo "dune: $(dune --version)"
          echo "rocq: $(rocq --print-version)"
  test-action-weekly:
    name: Run action (rocq weekly)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Run local action
        id: test-action
        uses: ./
        with:
          rocq-version: 'weekly'
      - name: Test installed tools
        run: |
          echo "rocq: $(rocq --print-version)"
  test-action-version:
    name: Run action (rocq v9.0)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Run local action
        id: test-action
        uses: ./
        with:
          rocq-version: '9.0.0'
      - name: Test installed tools
        run: |
          echo "rocq: $(rocq --print-version)"
